services:
  app:
    build:
      context: ./docker
    image: polda-php:latest
    container_name: polda-app
    volumes:
      - ./:/var/www/html
    networks:
      - polda_net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: polda-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - polda_net
    restart: unless-stopped

networks:
  polda_net:
    driver: bridge

volumes:
  db_data:
    driver: local